$fs = 0.01;

module connect_pads(
    positions, // vector of 3-vector, relative to component
    diameters, // diameter of holes, as number vector
    component_description // generated by script
) {
    
}